// kovdocs — static site generator for Kov documentation
// uses the Kov compiler's lexer for syntax highlighting
// bootstrap version: written in Rust, calls Kov's lexer

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: kovdocs <content_dir> <output_dir>");
        eprintln!("  reads .md files from content_dir");
        eprintln!("  generates .html files to output_dir");
        std::process::exit(1);
    }

    let content_dir = Path::new(&args[1]);
    let output_dir = Path::new(&args[2]);

    if !content_dir.exists() {
        eprintln!("error: {} does not exist", content_dir.display());
        std::process::exit(1);
    }

    fs::create_dir_all(output_dir).unwrap();

    let mut pages: Vec<Page> = Vec::new();

    // collect all .md files
    for entry in fs::read_dir(content_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().map(|e| e == "md").unwrap_or(false) {
            let content = fs::read_to_string(&path).unwrap();
            let name = path.file_stem().unwrap().to_str().unwrap().to_string();
            let (title, html) = parse_markdown(&content);
            pages.push(Page {
                name: name.clone(),
                title,
                html,
                source_path: path,
            });
        }
    }

    pages.sort_by(|a, b| a.name.cmp(&b.name));

    // generate HTML for each page
    for page in &pages {
        let nav = generate_nav(&pages, &page.name);
        let full_html = wrap_html(&page.title, &nav, &page.html);
        let out_path = output_dir.join(format!("{}.html", page.name));
        fs::write(&out_path, &full_html).unwrap();
        eprintln!("  {} → {}", page.source_path.display(), out_path.display());
    }

    // generate index
    let index_nav = generate_nav(&pages, "index");
    let index_content = pages
        .iter()
        .map(|p| format!("<li><a href=\"{}.html\">{}</a></li>", p.name, p.title))
        .collect::<Vec<_>>()
        .join("\n");
    let index_html = wrap_html(
        "Kov Documentation",
        &index_nav,
        &format!("<h1>Kov Documentation</h1>\n<p>generated by kovdocs</p>\n<ul>\n{}\n</ul>", index_content),
    );
    fs::write(output_dir.join("index.html"), &index_html).unwrap();

    // write CSS
    fs::write(output_dir.join("style.css"), CSS).unwrap();

    eprintln!("\n  done: {} pages generated", pages.len() + 1);
}

struct Page {
    name: String,
    title: String,
    html: String,
    source_path: PathBuf,
}

fn parse_markdown(md: &str) -> (String, String) {
    let mut html = String::new();
    let mut title = String::new();
    let mut in_code = false;
    let mut code_lang = String::new();
    let mut code_buf = String::new();
    let mut in_paragraph = false;

    for line in md.lines() {
        if line.starts_with("```") {
            if in_code {
                // end code block
                let highlighted = highlight_code(&code_buf, &code_lang);
                html.push_str(&format!(
                    "<pre><code class=\"lang-{}\">{}</code></pre>\n",
                    code_lang, highlighted
                ));
                code_buf.clear();
                in_code = false;
            } else {
                if in_paragraph {
                    html.push_str("</p>\n");
                    in_paragraph = false;
                }
                code_lang = line[3..].trim().to_string();
                if code_lang.is_empty() {
                    code_lang = "text".to_string();
                }
                in_code = true;
            }
            continue;
        }

        if in_code {
            code_buf.push_str(line);
            code_buf.push('\n');
            continue;
        }

        if line.is_empty() {
            if in_paragraph {
                html.push_str("</p>\n");
                in_paragraph = false;
            }
            continue;
        }

        if line.starts_with("# ") {
            if in_paragraph { html.push_str("</p>\n"); in_paragraph = false; }
            let text = &line[2..];
            if title.is_empty() { title = text.to_string(); }
            let id = text.to_lowercase().replace(' ', "-");
            html.push_str(&format!("<h1 id=\"{}\">{}</h1>\n", id, escape_html(text)));
        } else if line.starts_with("## ") {
            if in_paragraph { html.push_str("</p>\n"); in_paragraph = false; }
            let text = &line[3..];
            let id = text.to_lowercase().replace(' ', "-");
            html.push_str(&format!("<h2 id=\"{}\">{}</h2>\n", id, escape_html(text)));
        } else if line.starts_with("### ") {
            if in_paragraph { html.push_str("</p>\n"); in_paragraph = false; }
            let text = &line[4..];
            let id = text.to_lowercase().replace(' ', "-");
            html.push_str(&format!("<h3 id=\"{}\">{}</h3>\n", id, escape_html(text)));
        } else if line.starts_with("- ") {
            if in_paragraph { html.push_str("</p>\n"); in_paragraph = false; }
            html.push_str(&format!("<li>{}</li>\n", inline_format(&line[2..])));
        } else {
            if !in_paragraph {
                html.push_str("<p>");
                in_paragraph = true;
            } else {
                html.push(' ');
            }
            html.push_str(&inline_format(line));
        }
    }

    if in_paragraph { html.push_str("</p>\n"); }
    if title.is_empty() { title = "Untitled".to_string(); }

    (title, html)
}

fn inline_format(text: &str) -> String {
    let mut result = escape_html(text);
    // bold: **text**
    while let Some(start) = result.find("**") {
        if let Some(end) = result[start + 2..].find("**") {
            let inner = &result[start + 2..start + 2 + end].to_string();
            result = format!(
                "{}<strong>{}</strong>{}",
                &result[..start],
                inner,
                &result[start + 4 + end..]
            );
        } else {
            break;
        }
    }
    // inline code: `text`
    while let Some(start) = result.find('`') {
        if let Some(end) = result[start + 1..].find('`') {
            let inner = &result[start + 1..start + 1 + end].to_string();
            result = format!(
                "{}<code>{}</code>{}",
                &result[..start],
                inner,
                &result[start + 2 + end..]
            );
        } else {
            break;
        }
    }
    // links: [text](url)
    while let Some(bracket_start) = result.find('[') {
        if let Some(bracket_end) = result[bracket_start..].find("](") {
            let abs_bracket_end = bracket_start + bracket_end;
            if let Some(paren_end) = result[abs_bracket_end + 2..].find(')') {
                let text = &result[bracket_start + 1..abs_bracket_end].to_string();
                let url = &result[abs_bracket_end + 2..abs_bracket_end + 2 + paren_end].to_string();
                result = format!(
                    "{}<a href=\"{}\">{}</a>{}",
                    &result[..bracket_start],
                    url,
                    text,
                    &result[abs_bracket_end + 3 + paren_end..]
                );
            } else {
                break;
            }
        } else {
            break;
        }
    }
    result
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn highlight_code(code: &str, lang: &str) -> String {
    if lang != "kov" {
        return escape_html(code);
    }
    // use Kov's token kinds for highlighting
    let mut result = String::new();
    let chars: Vec<char> = code.chars().collect();
    let mut i = 0;

    while i < chars.len() {
        let c = chars[i];

        // comments
        if c == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
            result.push_str("<span class=\"comment\">");
            while i < chars.len() && chars[i] != '\n' {
                result.push_str(&escape_html(&chars[i].to_string()));
                i += 1;
            }
            result.push_str("</span>");
            continue;
        }

        // strings
        if c == '"' {
            result.push_str("<span class=\"string\">&quot;");
            i += 1;
            while i < chars.len() && chars[i] != '"' {
                result.push_str(&escape_html(&chars[i].to_string()));
                i += 1;
            }
            if i < chars.len() { i += 1; }
            result.push_str("&quot;</span>");
            continue;
        }

        // numbers
        if c.is_ascii_digit() {
            result.push_str("<span class=\"number\">");
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_' || chars[i] == 'x') {
                result.push(chars[i]);
                i += 1;
            }
            result.push_str("</span>");
            continue;
        }

        // identifiers and keywords
        if c.is_ascii_alphabetic() || c == '_' {
            let start = i;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let word: String = chars[start..i].iter().collect();
            let class = match word.as_str() {
                "fn" | "let" | "mut" | "if" | "else" | "loop" | "while" | "for" | "in"
                | "match" | "return" | "break" | "continue" | "struct" | "enum" | "trait"
                | "impl" | "board" | "interrupt" | "extern" | "static" | "const" | "type"
                | "import" | "try" | "true" | "false" => "keyword",
                "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "bool"
                | "void" | "usize" | "isize" => "type",
                _ => "",
            };
            if class.is_empty() {
                result.push_str(&word);
            } else {
                result.push_str(&format!("<span class=\"{}\">{}</span>", class, word));
            }
            continue;
        }

        // attributes
        if c == '#' {
            result.push_str("<span class=\"attr\">#");
            i += 1;
            if i < chars.len() && chars[i] == '[' {
                while i < chars.len() && chars[i] != ']' {
                    result.push_str(&escape_html(&chars[i].to_string()));
                    i += 1;
                }
                if i < chars.len() { result.push(']'); i += 1; }
            }
            result.push_str("</span>");
            continue;
        }

        result.push_str(&escape_html(&c.to_string()));
        i += 1;
    }

    result
}

fn generate_nav(pages: &[Page], current: &str) -> String {
    let mut nav = String::from("<nav>\n<ul>\n");
    nav.push_str(&format!(
        "<li{}><a href=\"index.html\">Home</a></li>\n",
        if current == "index" { " class=\"active\"" } else { "" }
    ));
    for page in pages {
        let active = if page.name == current { " class=\"active\"" } else { "" };
        nav.push_str(&format!(
            "<li{}><a href=\"{}.html\">{}</a></li>\n",
            active, page.name, page.title
        ));
    }
    nav.push_str("</ul>\n</nav>\n");
    nav
}

fn wrap_html(title: &str, nav: &str, content: &str) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — Kov</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="layout">
<aside>{nav}</aside>
<main>{content}</main>
</div>
<footer><p>generated by kovdocs — built with the kov compiler</p></footer>
</body>
</html>"#
    )
}

const CSS: &str = r#"
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Inter', system-ui, sans-serif; background: #09090b; color: #e4e4e7; line-height: 1.7; }
.layout { display: grid; grid-template-columns: 240px 1fr; min-height: 100vh; }
aside { background: #0f0f11; border-right: 1px solid #1c1c1f; padding: 24px 16px; position: sticky; top: 0; height: 100vh; overflow-y: auto; }
nav ul { list-style: none; }
nav li { margin: 4px 0; }
nav a { color: #a1a1a6; text-decoration: none; font-size: 14px; padding: 6px 12px; display: block; border-radius: 6px; transition: all 0.15s; }
nav a:hover { color: #e4e4e7; background: rgba(255,255,255,0.05); }
nav .active a { color: #fff; background: rgba(255,255,255,0.08); }
main { max-width: 720px; padding: 48px 40px; }
h1 { font-size: 32px; font-weight: 700; margin: 0 0 16px; letter-spacing: -0.02em; color: #fafafa; }
h2 { font-size: 24px; font-weight: 600; margin: 40px 0 12px; letter-spacing: -0.01em; color: #fafafa; border-bottom: 1px solid #1c1c1f; padding-bottom: 8px; }
h3 { font-size: 18px; font-weight: 600; margin: 32px 0 8px; color: #e4e4e7; }
p { margin: 0 0 16px; color: #a1a1a6; }
li { color: #a1a1a6; margin: 4px 0 4px 24px; }
a { color: #60a5fa; }
code { font-family: 'JetBrains Mono', monospace; background: #161618; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #e4e4e7; }
pre { background: #0f0f11; border: 1px solid #1c1c1f; border-radius: 8px; padding: 16px; margin: 16px 0; overflow-x: auto; }
pre code { background: none; padding: 0; font-size: 13px; line-height: 1.6; }
.keyword { color: #c084fc; }
.type { color: #60a5fa; }
.string { color: #86efac; }
.number { color: #fbbf24; }
.comment { color: #52525b; font-style: italic; }
.attr { color: #f87171; }
strong { color: #e4e4e7; }
footer { text-align: center; padding: 24px; color: #52525b; font-size: 13px; border-top: 1px solid #1c1c1f; }
@media (max-width: 768px) { .layout { grid-template-columns: 1fr; } aside { position: static; height: auto; } }
"#;
